<div class="block block-custom-sidebar" data-bind="scope: 'customSidebar'" data-role="custom-products-sidebar">
    <div class="block-title" style="padding-bottom: 20px;">
        <strong id="block-custom-sidebar-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Custom Sidebar')) ?></strong>
    </div>
<!-- ko if: customSidebar().count -->
    <div class="talexan-custom-sidebar" data-bind="css: {'no-display': !customSidebar().count}">
        <ul id="sidebar-items" class="product-items" data-bind="foreach: customSidebar().items">
            <li class="product-item">
                <div style="height: 72px; clear: all;">
                    <div class="container-product-photo" data-bind="style: {'float': 'left', 'margin': '2px', 'height': '64px'}">
                        <a href="#" class="product-item-photo" data-bind="attr: {href: href}">
                            <span class="product-image-container">
                                <img data-bind="attr: {class: classImg, src: src, alt: labelImg}"
                                        src="#"
                                        loading="lazy" width="48" height="64"
                                        alt="" />
                            </span>
                        </a>
                    </div>
                    <div class="product details product-item-details random3-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="#" data-bind="attr: {href: href}, text: name"></a>
                        </strong>
                        <div class="price-box price-final_price" data-role="priceBox" >
                            <span class="price" data-bind="html: price"></span>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
<!-- /ko -->
<!-- ko ifnot: customSidebar().count -->
    <div class="empty"><?= $block->escapeHtml(__('Wait...')) ?></div>
<!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=custom-products-sidebar]": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customSidebar": {
                        "component": "Talexan_Random3\/js\/custom-sidebar"
                    }
                }
            }
        }

    }
</script>